config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    get "follow", to: "pages#follow"
    get "unfollow", to: "pages#unfollow"
  end
  root to: 'meals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :bookings, only: [ :index, :show, :new, :create, :destroy ]
    get "favorite", to: 'pages#favorite'
    get 'unfavorite', to: 'pages#unfavorite'
    get "host", to: "pages#host"
  end


  get "profile", to: "pages#profile", as: "profile"
  get "saves", to: "pages#saves", as: "saves"
  get "follows", to: "pages#follows", as: "follows"
  get "followers", to: "pages#followers", as: "followers"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :user, presence: true
  validates :meal, presence: true
  validates :time, presence: true
  validates :price, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ActiveRecord::Base
  extend ActsAsFavoritor::FavoritorLib
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update(blocked: true)
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  acts_as_favoritable

  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :bookings

  validates :user_id, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :price, presence: true
  validates :category, presence: true, inclusion: {
    in: ['Chinese Food', 'Asian Food', 'Western Food', 'Alcohol-related', 'Dessert and Coffee'],
  message: "%{value} is not a valid category" }
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_favoritor
  acts_as_favoritable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :meals, dependent: :destroy
  has_many :bookings

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :interest, :description, :host, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @meal = Meal.find(params[:meal_id])
  end

  def create
    @meal = Meal.find(params[:meal_id])
    @booking = Booking.new(booking_params)
    @booking.meal = @meal
    @booking.price = @meal.price
    @booking.user = current_user
    if @booking.save
      redirect_to meal_booking_path(@meal, @booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path
  end

  private
  def booking_params
    params.require(:booking).permit(:time)
  end
end

app/controllers/meal_controller.rb
class MealController < ApplicationController
  before_action :find_meal, only: [ :show, :edit, :update, :destroy ]

  def index
    @meals = Meal.all
  end

  def show
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to meals_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
      redirect_to @meal
    else
      render :edit
    end
  end

  def destroy
    @meal.destroy
    redirect_to meals_path
  end

  private
  def find_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :description, :price, :category)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :find_meal, only: [ :show, :edit, :update, :destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @meals = Meal.all
  end

  def show
  end

  def new
    if current_user.host
      @meal = Meal.new
    else
      redirect_to profile_path
    end
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    if @meal.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
      redirect_to @meal
    else
      render :edit
    end
  end

  def destroy
    @meal.destroy
    redirect_to profile_path
  end

  private
  def find_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :description, :price, :category, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :host ]
  before_action :find_current_user, only: [ :profile, :favorite, :unfavorite, :saves, :follows ]
  before_action :find_meal, only: [ :favorite, :host, :unfavorite ]

  def profile
  end

  def host
    @host = @meal.user
  end

  def favorite
    @user.favorite @meal
    redirect_to request.referrer
  end

  def unfavorite
    @user.remove_favorite @meal
    redirect_to request.referrer
  end

  def saves
    @meals = current_user.favorited_by_type('Meal')
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.favorite @user
    redirect_to request.referrer
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.remove_favorite @user
    redirect_to request.referrer
  end

  def follows
    @users = current_user.favorited_by_type('User')
  end

  def followers
    @users = current_user.favoritors
  end

  private
  def find_current_user
    if user_signed_in?
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  end

  def find_meal
    @meal = Meal.find(params[:meal_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@meal, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs form-inline">
    <%= f.input :time %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.submit "Book The Meal", class: "btn btn-success", data: { confirm: "Please Confirm: You are booking #{@meal.name} hosted by #{@meal.user.name} with a price of #{@meal.price}" } %>
  </div>
<% end %>

app/views/bookings/confirmation.html.erb
<div class = “confirmation”>
   <h4 class=“fas fa-cancel-circle” > You’ve successfully booked the meal!</h4>
   <h5>Below are the details of your order:</h5>
   <h5>Your meal: <%= Meal.find(params[:meal_id]).name %></h5>
   <h5>Price: <%= Meal.find(params[:meal_id]).price %></h5>
   <h5>Host: <%= Meal.find(params[:meal_id]).user.name %></h5>
   <h5>We’ve sent contact information of the gost to your email inbox.</h5>
   <h5>Please say hello to your host!</h5>
   <h5>Enjoy your meal!</h5>
</div>

app/views/bookings/new.html.erb
<div class="wrapper wrapper-img">
  <div class="div-design">
    <h2 class="font-color">Book This Meal</h2>
    <p class="font-size-20">Meal: <%= @meal.name %></p>
    <p class="font-size-20">Host: <%= @meal.user.name %></p>
    <p class="font-size-20">Price: <%= @meal.price %></p>
    <%= render 'form', booking: @booking %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="confirmation">
  <ul>
    <h3 class="fas fa-check-circle"> You’ve successfully booked the meal!</h3>
    <h5>Below are the details of your order:</h5>
    <h4 font-weight= bold >Your meal: <%= @booking.meal.name %></h4>
    <h4>Price: <%= @booking.meal.price %></h4>
    <h4>Time: <%= @booking.time %></h4>
    <h4>Host: <%= @booking.meal.user.name %></h4>
    <h5>We’ve sent contact information of the foodie guide to your email inbox.</h5>
    <h5>Please say hello to your foodie guide!</h5>
    <h5>Enjoy your meal!</h5>
    <div class="font-color-white"><%= link_to 'Cancel this', meal_booking_path(@booking.meal, @booking), method: :delete, data: { confirm: "Are you sure?" } %></div>
    <div class="font-color-white"><%= link_to 'Continue to your profile page', profile_path %></div>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= simple_form_for(@meal) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :category, as: :radio_buttons, collection: ['Chinese Food', 'Asian Food', 'Western Food', 'Alcohol-related', 'Dessert and Coffee'] %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success"%>
  </div>
<% end %>

app/views/meals/destroy.html.erb
<h1>Meal#destroy</h1>
<p>Find me in app/views/meal/destroy.html.erb</p>

app/views/meals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col col-sm-8 col-sm-offset-2">
      <h1>Update Meal</h1>
      <%= render 'form', meal: @meal %>
      <%= link_to 'Back', profile_path %>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.45) 0%, rgba(0,36,61,0.45) 50%), url('https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8a5e4cac8bcaf69ffaf5d3b1c2b063e4&auto=format&fit=crop&w=1950&q=80');">
  <div class="banner-content">
    <h1>Foodie</h1>
    <h3>Interesting People & Home-Cooked Meals</h3>
  </div>
</div>
</div class="wrapper-main-page">
<div class="text-middle"><strong><h2 class="font-color ">Explore</h2></strong></div>
<div class="container">
  <div class="row">
    <br>
    <% @meals.each do |meal| %>
      <div class="col-xs-12 col-sm-4 card-padding">
        <%= render 'shared/card', meal: meal %>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/new.html.erb
<div class="wrapper wrapper-img2 ">
  <div class="row">
    <div class="col col-sm-12 col-sm-offset-0">
      <div class="div-design">
        <h3 class="font-color">Add A New Meal To Your Own Profile</h3>
        <%= render 'form', meal: @meal %>
        <br>
        <%= link_to 'Back', profile_path %>
      </div>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="profile text-center">
    <div class="main1">
      <%= cl_image_tag @meal.photo, height: 330, width: 400, crop: :fill %>
    </div>
    <div class="main2">
      <div class="main-content">
        <img src=<%= @meal.user.photo %> alt="" width="80" class="img-circle">
        <h2><%= link_to @meal.user.name, meal_host_path(@meal) %></h2>
        <p><%= @meal.user.email %></p>
        <%= link_to 'Follow', user_follow_path(@meal.user), class: "btn btn-lg" %>
      </div>
    </div>
    <div class="description1">
      <div class="description-content">
        <h2 class="font-size-22"><%= @meal.name %></h2>
        <p><%= @meal.category %></p>
        <strong>
          <p class="font-size-18 font-color-black"><%= @meal.price %></p>
        </strong>
        <p class="text-justify font-size-16 font-color-black"><%= @meal.description %></p>
        <% if @meal.favorited_by? current_user %>
          <%= link_to 'Unsave',meal_unfavorite_path(@meal), class: "btn btn-lg", id:"font-white-book" %>
        <% else %>
          <%= link_to 'Save',meal_favorite_path(@meal), class: "btn btn-lg", id:"font-white-book" %>
        <% end %>
        <%= link_to 'Book',new_meal_booking_path(@meal), class: "btn btn-lg", id:"font-white-book" %>
      </div>
    </div>
    <div class="description2">
      <div class="description-content">
        <h2 class="font-size-22">More about <%= @meal.user.name %></h2>
        <p class="text-justify font-size-16 font-color-black"><%= @meal.user.description %></p>
        <p>
          <% unless @meal.user.interest.nil? %>
            <% @meal.user.interest.each do |category| %>
              <%= category %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <p><%= link_to 'See All Meals', meals_path %></p>
</div>

app/views/pages/apply.html.erb
<h2>Apply To Become A Foodie</h2>
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>
    <%= f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
    <%= f.input :password_confirmation, required: false %>
    <%= f.input :current_password, hint: "we need your current password to confirm your changes", required: true %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>
<h3>Cancel my account</h3>
<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
<%= link_to "Back", :back %>

app/views/pages/followers.html.erb
<div class="wrapper4 wrapper-img2 padding-top-50">
  <div class="row">
    <div class="col col-sm-12 col-sm-offset-0">
      <div class="div-design">
        <h2>Followers</h2>
        <div>
          <% @users.each do |user| %>
            <%= user.name %>
            <%= user.description %>
          <% end %>
        </div>
        <%= link_to 'Back', profile_path %>
      </div>
    </div>
  </div>
</div>

app/views/pages/follows.html.erb
<div class="wrapper4 wrapper-img2 padding-top-50">
  <div class="row">
    <div class="col col-sm-12 col-sm-offset-0">
      <div class="div-design">
        <h2>Following</h2>
        <div>
          <% @users.each do |user| %>
            <%= user.name %>
            <%= user.description %>
          <% end %>
        </div>
        <%= link_to 'Back', profile_path %>
      </div>
    </div>
  </div>
</div>

app/views/pages/host.html.erb
<div class="container">
  <div class="profile">
    <div class="main4">
      <div class="main-content">
        <%= image_tag "#{@host.photo}", width: "80", class: "img-circle" %>
        <h2><%= @host.name %></h2>
        <p><%= @host.email %></p>
        <% if @host.favorited_by? current_user %>
          <%= link_to 'Unfollow', user_unfollow_path(@host), class: "btn btn-lg"%>
        <% else %>
          <%= link_to 'Follow', user_follow_path(@host), class: "btn btn-lg"%>
        <% end %>
      </div>
    </div>
    <div class="description3">
      <div class="description-content">
        <h2><%= @host.meals.name %></h2>
        <div>
          <% @host.meals.each do |meal| %>
            <br>
            <div class="host-container">
              <div><%= image_tag "#{meal.photo}", width: "100" %></div>
              <div class="padding-left-50">
                <div><%= link_to meal.name, meal_path(meal) %></div>
                <div><%= meal.description %></div>
                <div><%= meal.price %></div>
                <div><%= meal.category %></div>
              </div>
            </div>
          <% end %>
        </div>
        <p><%= link_to 'See All Meals', meals_path %></p>
      </div>
    </div>
    <div class="description4">
      <div class="description-content">
        <h2>More about <%= @host.name %></h2>
        <p><%= @host.description %></p>
        <p>
          <% unless @host.interest.nil? %>
            <% @host.interest.each do |category| %>
              <button class="btn-medium"><%= category %></button>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="wrapper-img3">
  <div class="profile-container">
    <div id="profile-id padding-left">
      <div class="main5 text-center", id="profile-id">
        <div class="main-content">
          <%= image_tag "#{@user.photo}", class: "img-circle", width: "140" %>
          <h3 class="font-color"><%= @user.name %></h3>
          <div>
            <table>
              <tr class="font-size-12 text-center" id="profile-table">
                <th><%= link_to "Following", follows_path %></th>
                <th><%= link_to 'Followers', followers_path %></th>
              </tr>
              <tr class="font-size-12 text-center">
                <td><%= @user.favorited_by_type_count 'User' %></td>
                <td><%= @user.favoritors_count %></td>
              </tr>
            </table>
          </div>
          <p><%= "You are a host" if @user.host %>
          </p>
          <p><%= @user.email %></p>
          <p><%= @user.description %></p>
          <% unless @user.interest.nil? %>
            <% @user.interest.each do |category| %>
              <p><%= category %>
                <p>
                <% end %>
              <% end %>
              <% if @user.host %>
                <%= link_to 'Add A New Meal', new_meal_path, class: "btn-medium green" %>
              <% else %>
                <%= link_to 'Become A Host', edit_user_registration_path, class: "btn-medium green" %>
              <% end %>
              <div class="padding-top"><%= link_to 'Back', meals_path%></div>
            </div>
          </div>
        </div>
        <div class="cards-container profile-margin-top">
          <div class="row">
            <div class="col-xs-12 col-xs-offset-0">
              <div class="description5">
                <div class="description-content">
                  <div>
                    <h3>Hosting:</h3>
                    <table>
                      <tr class="font-size-12 text-center" id="profile-table">
                        <th>Booked Meal</th>
                        <th>Incoming User</th>
                        <th>Scheduled Time</th>
                      </tr>
                      <% @user.meals.each do |meal| %>
                        <% meal.bookings.each do |booking| %>
                          <tr class="font-size-12 text-center">
                            <td><%= booking.meal.name %></td>
                            <td><%= booking.user.name %></td>
                            <td><%= booking.time %></td>
                            <td class="margin-left"><%= link_to 'Decline', meal_booking_path(booking.meal, booking), method: :delete, data: { confirm: "Are you sure?" } %></td>
                          </tr>
                        <% end %>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
              <div class="description5">
                <div class="description-content">
                  <div>
                    <h3>Attending:</h3>
                    <% @user.bookings.each do |book| %>
                      <%= link_to book.meal.name, meal_booking_path(book.meal, book) %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
          <div class="cards-container profile-margin-top">
            <div class="row">
              <div class="col-xs-12 col-xs-offset-0">
                <div class="description5">
                  <div class="description-content">
                    <h3>Saved Meals</h3>
                    <% @user.favorited_by_type('Meal').each do |meal| %>
                      <%= link_to meal.name, meal_path(meal) %>
                    <% end %>
                    <h2><%= link_to "Details", saves_path %></h2>
                  </div>
                </div>
                <% if @user.host %>
                  <div class="description8">
                    <strong>
                      <h3 class="font-color-black">Meals</h3>
                    </strong>
                    <% @user.meals.each do |meal| %>
                      <br>
                      <div class="description-content green">
                        <div><%= link_to meal.name, meal_path(meal) %></div>
                        <br>
                        <div class="meal-card-description">
                          <div class="meals-card-description-padding-top">
                            <%= link_to meal_path(meal) do %>
                              <%= image_tag "#{meal.photo}", width: "100" %>
                            <% end %>
                          </div>
                          <div class="meals-card-description-margin-left">
                            <div><%= meal.description %></div>
                            <strong>
                              <div><%= meal.price %></div>
                            </strong>
                            <strong><%= link_to 'Update', edit_meal_path(meal), class: "btn-medium green"%></strong>
                            <% if meal.bookings.nil? %>
                              <strong><%= link_to 'Delete', meal_path(meal), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-medium green"%></strong>
                            <% else %>
                              <strong><%= link_to 'Delete', profile_path,  data: { confirm: "You cannot delete this because it is currently booked by someone." }, class: "btn-medium green"%></strong>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/saves.html.erb
<div class="wrapper4 wrapper-img2 padding-top-50">
  <div class="row">
    <div class="col col-sm-12 col-sm-offset-0">
      <div class="div-design">
        <h2>Saved Meals</h2>
        <% @meals.each do |meal| %>
          <%= link_to meal.name, meal %>
          <%= meal.price %>
          <%= meal.user.name %>
        <% end %>
        <%= link_to 'Back', profile_path %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="column">
  <!-- Post-->
  <div class="post-module">
    <!-- Thumbnail-->
    <div class="thumbnail">
      <%= cl_image_tag meal.photo, height: 300, width: 400, crop: :fill %>
    </div>
    <!-- Post Content-->
    <div class="post-content">
      <div class="category"><%= meal.category %></div>
      <h1 class="title"><%= link_to meal.name, meal %></h1>
      <h2 class="sub_title"><%= link_to meal.user.name, meal_host_path(meal) %></h2>
      <p class="description">
        <%= "About Me" %>
        <br>
        <%= meal.user.description %>
      </p>
      <%= image_tag "#{meal.user.photo}", class: "card-user" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "th.jpg", height: 50 %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to t(".become_a_host", default: "Become a Host"), edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Saved Meals", saves_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "#{current_user.photo}", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".current_user.name", default: current_user.name) %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link btn-treehouse" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href=<%= user_path(current_user) %>><%= current_user.name %></a></li>
          <li><a href="">Meals</a></li>
        </ul>
      </div>
    <% else %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Log in", new_user_session_path %></li>
      </ul>
    <% end %>
  </div>
</div>
</div>